require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'
use_frameworks!(:linkage => :static)
install! 'cocoapods', :deterministic_uuids => false

def react_native_modules()
  
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )

  # Pods for RNSDKExample
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/React/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => "../node_modules/react-native/"
  pod 'React-Core', :path => "../node_modules/react-native/"
  pod 'React-CoreModules', :path => "../node_modules/react-native/React/CoreModules"
  pod 'React-RCTAppDelegate', :path => "../node_modules/react-native/Libraries/AppDelegate"
  pod 'React-RCTActionSheet', :path => "../node_modules/react-native/Libraries/ActionSheetIOS"
  pod 'React-RCTAnimation', :path => "../node_modules/react-native/Libraries/NativeAnimation"
  pod 'React-RCTBlob', :path => "../node_modules/react-native/Libraries/Blob"
  pod 'React-RCTImage', :path => "../node_modules/react-native/Libraries/Image"
  pod 'React-RCTLinking', :path => "../node_modules/react-native/Libraries/LinkingIOS"
  pod 'React-RCTNetwork', :path => "../node_modules/react-native/Libraries/Network"
  pod 'React-RCTSettings', :path => "../node_modules/react-native/Libraries/Settings"
  pod 'React-RCTText', :path => "../node_modules/react-native/Libraries/Text"
  pod 'React-RCTVibration', :path => "../node_modules/react-native/Libraries/Vibration"
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'
  pod 'React-rncore', :path => "../node_modules/react-native/ReactCommon"
  pod 'React-cxxreact', :path => "../node_modules/react-native/ReactCommon/cxxreact"
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-debug', :path => "../node_modules/react-native/ReactCommon/react/debug"
  pod 'React-utils', :path => "../node_modules/react-native/ReactCommon/react/utils"
  pod 'React-jsiexecutor', :path => "../node_modules/react-native/ReactCommon/jsiexecutor"
  pod 'React-jsinspector', :path => "../node_modules/react-native/ReactCommon/jsinspector"

  pod 'React-callinvoker', :path => "../node_modules/react-native/ReactCommon/callinvoker"
  pod 'React-runtimeexecutor', :path => "../node_modules/react-native/ReactCommon/runtimeexecutor"
  pod 'React-runtimescheduler', :path => "../node_modules/react-native/ReactCommon/react/renderer/runtimescheduler"
  pod 'React-perflogger', :path => "../node_modules/react-native/ReactCommon/reactperflogger"
  pod 'React-logger', :path => "../node_modules/react-native/ReactCommon/logger"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'React-NativeModulesApple', :path => "../node_modules/react-native/ReactCommon/react/nativemodule/core/platform/ios"
  pod 'Yoga', :path => "../node_modules/react-native/ReactCommon/yoga"

  pod 'DoubleConversion', :podspec => "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "../node_modules/react-native/third-party-podspecs/glog.podspec"
  pod 'boost', :podspec => "../node_modules/react-native/third-party-podspecs/boost.podspec"
  pod 'RCT-Folly', :podspec => "../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec"

  pod 'React-Codegen', :path => "build/generated/ios"

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'
  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'
  pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'  
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  pod 'react-native-cookies', :path => '../node_modules/@react-native-cookies/cookies'

end

target 'RNSDKExample2' do
  react_native_modules()
  # config = use_native_modules!

  # # Flags change depending on the env values.
  # flags = get_default_flags()

  # use_react_native!(
  #   :path => config[:reactNativePath],
  #   # to enable hermes on iOS, change `false` to `true` and then install pods
  #   :hermes_enabled => flags[:hermes_enabled],
  #   :fabric_enabled => flags[:fabric_enabled],
  #   # An absolute path to your application root.
  #   :app_path => "#{Pod::Config.instance.installation_root}/.."
  # )

  target 'RNSDKExample2Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  # post_install do |installer|
  #   react_native_post_install(installer)
  #   __apply_Xcode_12_5_M1_post_install_workaround(installer)
  # end
end

target 'RNSDK' do
  react_native_modules()
end

post_install do |installer|
  react_native_post_install(installer)
  __apply_Xcode_12_5_M1_post_install_workaround(installer)
end