export const VIEW_TYPE = {
  BACKGROUND_TASK: 'BACKGROUND_TASK',
  STORE_CONNECTIONS_LIST: 'STORE_CONNECTIONS_LIST',
  CONNECT_UPDATE_STORE: 'CONNECT_UPDATE_STORE',
}

export const EVENT_TYPES = {
  COOKLIST_SDK_EVENT: 'cooklist_sdk_event',
  COOKLIST_SDK_VIEW_COMPLETE_EVENT: 'cooklist_sdk_view_complete_event',
}